export const CATEGORIES = [
    {
      id: 1,
      name: "아우터",
      subcategories: [
        { subCategoryId: 1001, name: "패딩" },
        { subCategoryId: 1002, name: "경량패딩" },
        { subCategoryId: 1003, name: "집업가디건" },
        { subCategoryId: 1004, name: "가디건" },
        { subCategoryId: 1005, name: "후리스" },
        { subCategoryId: 1006, name: "점퍼" },
        { subCategoryId: 1007, name: "야상" },
        { subCategoryId: 1008, name: "블루종/항공" },
        { subCategoryId: 1009, name: "코트" },
        { subCategoryId: 1010, name: "트렌치코트" },
        { subCategoryId: 1011, name: "자켓" },
        { subCategoryId: 1012, name: "데님자켓" },
        { subCategoryId: 1013, name: "조끼/베스트" },
        { subCategoryId: 1014, name: "후드집업" },
        { subCategoryId: 1015, name: "바람막이" },
        { subCategoryId: 1016, name: "트랙탑 져지" },
      ],
    },
    {
      id: 2,
      name: "상의",
      subcategories: [
        { subCategoryId: 2001, name: "니트/스웨터" },
        { subCategoryId: 2002, name: "니트조끼" },
        { subCategoryId: 2003, name: "니트집업(반집업)" },
        { subCategoryId: 2004, name: "브이넥 니트" },
        { subCategoryId: 2005, name: "라운드넥 니트" },
        { subCategoryId: 2006, name: "후드티" },
        { subCategoryId: 2007, name: "맨투맨" },
        { subCategoryId: 2008, name: "블라우스" },
        { subCategoryId: 2009, name: "블레이져" },
        { subCategoryId: 2010, name: "셔츠" },
        { subCategoryId: 2011, name: "체크셔츠" },
        { subCategoryId: 2012, name: "스트라이프셔츠" },
        { subCategoryId: 2013, name: "솔리드셔츠" },
        { subCategoryId: 2014, name: "반팔" },
        { subCategoryId: 2015, name: "반팔 티셔츠" },
        { subCategoryId: 2016, name: "긴팔" },
        { subCategoryId: 2017, name: "롱슬리브" },
        { subCategoryId: 2018, name: "민소매" },
        { subCategoryId: 2019, name: "원피스" },
      ],
    },
    {
      id: 3,
      name: "하의",
      subcategories: [
        { subCategoryId: 3001, name: "스트레이트 일자핏 청바지"},
        { subCategoryId: 3002, name: "스키니 슬림 청바지" },
        { subCategoryId: 3003, name: "슬랙스" },
        { subCategoryId: 3004, name: "반바지" },
        { subCategoryId: 3005, name: "치마" },
        { subCategoryId: 3006, name: "면바지/치노팬츠" },
      ],
    },
    {
      id: 4,
      name: "신발",
      subcategories: [
        { subCategoryId: 4001, name: "운동화/스니커즈" },
        { subCategoryId: 4002, name: "구두" },
        { subCategoryId: 4003, name: "샌들/슬리퍼" },
        
      ],
    },
    {
      id: 5,
      name: "키즈",
      subcategories: [
        { subCategoryId: 5001, name: "패딩" },
        { subCategoryId: 5002, name: "상하복/세트" },
        { subCategoryId: 5003, name: "원피스" },
        { subCategoryId: 5004, name: "자켓/점퍼" },
        { subCategoryId: 5005, name: "가디건/조끼" },
        { subCategoryId: 5006, name: "셔츠/남방" },
        { subCategoryId: 5007, name: "티셔츠" },
        { subCategoryId: 5008, name: "바지" },
      ],
    }
  ];